package net.dblsaiko.qcommon.cfg.core.persistence;

import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.dblsaiko.qcommon.cfg.core.api.ExecSource;
import net.dblsaiko.qcommon.cfg.core.api.LinePrinter;
import net.dblsaiko.qcommon.cfg.core.api.impl.ConfigApi;
import net.dblsaiko.qcommon.cfg.core.api.persistence.PersistenceListener;
import net.dblsaiko.qcommon.cfg.core.cmdproc.CommandDispatcher;

public class PersistenceManager {

    private final Set<PersistenceListener> listeners = new HashSet<>();
    private final CommandDispatcher dispatcher;

    public PersistenceManager(CommandDispatcher dispatcher) {
        this.dispatcher = dispatcher;
    }

    public void addListener(PersistenceListener listener) {
        listeners.add(listener);
    }

    public void save() {
        Map<String, Set<PersistenceListener>> map = new HashMap<>();
        for (PersistenceListener listener : listeners) {
            for (String file : listener.files()) {
                map.computeIfAbsent(file, _file -> new HashSet<>()).add(listener);
            }
        }

        Path configDir = FabricLoader.getInstance().getConfigDirectory().toPath();

        map.forEach((file, listeners) -> {
            Path filePath = configDir.resolve(String.format("%s.cfg", file));

            if (filePath.startsWith(configDir)) {
                List<String> lines = new ArrayList<>();
                LinePrinter output = s -> lines.addAll(Arrays.asList(s.split("\n")));

                output.printf("// File: %s.cfg", file);
                output.printf("// Generated by qcommon-cfg.");
                output.print();
                listeners.forEach($ -> $.write(file, output));

                try {
                    Files.createDirectories(filePath.getParent());
                    Files.write(filePath, lines, StandardCharsets.UTF_8);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    public void load() {
        listeners.stream()
            .flatMap($ -> $.files().stream())
            .distinct()
            .forEach(file -> dispatcher.exec(String.format("exec %s", ConfigApi.INSTANCE.escape(file)), ExecSource.EVENT));
    }

}
